// <auto-generated />
using BOI.BOIApplications.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOI.BOIApplications.Persistence.Migrations.BOI2Db
{
    [DbContext(typeof(BOI2DbContext))]
    [Migration("20220421090253_changeName")]
    partial class changeName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOAnnualTurnover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnnualTurnover")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AOAnnualTurnover");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOCompanyType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("AOCompanyType");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOHighestEducationalQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HighestEducationalQualification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AOHighestEducationalQualification");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOIdentificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IdentificationType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AOIdentificationType");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOMaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AOMaritalStatus");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOStakeholderCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("StakeholderCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AOStakeholderCapacity");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.AccountOpeningModels.AOTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AOTitle");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.Bank", b =>
                {
                    b.Property<int>("bank_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bank_id"), 1L, 1);

                    b.Property<string>("bank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bank_id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCCollateralPledgedExistingLoan", b =>
                {
                    b.Property<int>("collateral_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("collateral_id"), 1L, 1);

                    b.Property<string>("collateral_pledged")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("collateral_id");

                    b.ToTable("MCCollateralPledgedExistingLoans");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCCollateralTypeProposedCollateral", b =>
                {
                    b.Property<int>("collateral_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("collateral_id"), 1L, 1);

                    b.Property<string>("collateral_type_proposed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("collateral_id");

                    b.ToTable("MCCollateralTypeProposedCollateral");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCIndustrySector", b =>
                {
                    b.Property<int>("ind_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ind_id"), 1L, 1);

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ind_id");

                    b.ToTable("MCIndustrySector");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCLoanClass", b =>
                {
                    b.Property<int>("loan_class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loan_class_id"), 1L, 1);

                    b.Property<string>("loan_class")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("loan_class_id");

                    b.ToTable("MCLoanClass");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCLoanPurpose", b =>
                {
                    b.Property<int>("loan_purpose_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loan_purpose_id"), 1L, 1);

                    b.Property<string>("loan_purpose")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("loan_purpose_id");

                    b.ToTable("MCLoanPurpose");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCLoanType", b =>
                {
                    b.Property<int>("loan_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loan_type_id"), 1L, 1);

                    b.Property<string>("loan_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("loan_type_id");

                    b.ToTable("MCLoanType");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCMoratorium", b =>
                {
                    b.Property<int>("moratorium_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("moratorium_id"), 1L, 1);

                    b.Property<string>("moratorium")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("moratorium_id");

                    b.ToTable("MCMoratorium");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCProduct", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"), 1L, 1);

                    b.Property<string>("product")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("product_id");

                    b.ToTable("MCProducts");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCRepaymentPlan", b =>
                {
                    b.Property<int>("repayment_plan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("repayment_plan_id"), 1L, 1);

                    b.Property<string>("repayment_plan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("repayment_plan_id");

                    b.ToTable("MCRepaymentPlan");
                });

            modelBuilder.Entity("BOI.BOIApplications.Domain.Entities.MicroCreditModels.MCSourceOfFund", b =>
                {
                    b.Property<int>("source_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("source_id"), 1L, 1);

                    b.Property<string>("source_funds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("source_id");

                    b.ToTable("MCSourceOfFunds");
                });
#pragma warning restore 612, 618
        }
    }
}
